### ISSUE TITLE
got an unexpected keyword argument 'themes_file'

### ISSUE THREAD

**Issue by Pemkaweb** [CyniaAI/BuilderGPT#33]
I get this error at startup ui.py

Python version 3.12.4, requirements are installed

```
Traceback (most recent call last):
  File "BuilderGPT-main\ui.py", line 285, in <module>
    root = CreateQGUI(title="BuilderGPT",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "BuilderGPT-main\cube_qgui\factory.py", line 52, in __init__
    self.root.style = Style(**QStyle.default)
                      ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Style.__new__() got an unexpected keyword argument 'themes_file'
```

**Comment by LeeTrongjNghiax** [comment]
> I get this error at startup ui.py
> 
> Python version 3.12.4, requirements are installed
> 
> ```
> Traceback (most recent call last):
>   File "BuilderGPT-main\ui.py", line 285, in <module>
>     root = CreateQGUI(title="BuilderGPT",
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "BuilderGPT-main\cube_qgui\factory.py", line 52, in __init__
>     self.root.style = Style(**QStyle.default)
>                       ^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: Style.__new__() got an unexpected keyword argument 'themes_file'
> ```

you can modify requirement.txt in the root folder to fixed this

old file:

- openai>=1.13.3
- pyyaml
- cx_Freeze
- playwright
- uuid
- ttkbootstrap

new file:

- openai>=1.13.3
- pyyaml
- cx_Freeze
- playwright
- uuid
- ttkbootstrap==0.5.1

**Comment by Pemkaweb** [comment]
Thanks a lot! :)
