### ISSUE TITLE
[Solved] TypeError: Style.new() got an unexpected keyword argument 'themes_file'

### ISSUE THREAD

**Issue by SAMPLAYZBLOX** [CyniaAI/BuilderGPT#37]
C:\Users\name\Downloads\BuilderGPT-main\BuilderGPT-main>python ui.py
Traceback (most recent call last):
  File "C:\Users\name\Downloads\BuilderGPT-main\BuilderGPT-main\ui.py", line 285, in <module>
    root = CreateQGUI(title="BuilderGPT",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\name\Downloads\BuilderGPT-main\BuilderGPT-main\cube_qgui\factory.py", line 52, in __init__
    self.root.style = Style(**QStyle.default)
                      ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Style.__new__() got an unexpected keyword argument 'themes_file'

C:\Users\name\Downloads\BuilderGPT-main\BuilderGPT-main>

**Comment by Zhou-Shilin** [comment]
Hello!
Try reinstall ttkbootstrap==0.5.1:
```bash
pip install ttkbootstrap==0.5.1 --force-reinstall
```

**Comment by lol00-creator** [comment]
thanks it works for me now
